name: CI PIPELINE

on:
  workflow_dispatch:
    inputs:
      skip-push:
        description: 'Skip Docker image push to Docker Hub'
        required: false
        default: 'false'
        type: boolean

jobs:
  lint-and-test:
    name: Linting and testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        id: install-dep
        run: npm ci

      - name: Run Lint
        id: npm-lint
        run: npm run lint

      - name: Run Test
        id: npm-ci-test
        run: npm run test

  build-and-push:
    name: Build and push docker image
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Login to Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        id: docker-build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/github-action-schoolMariem .

      - name: Push Docker image to Docker Hub
        id: docker-push
        if: inputs.skip-push == 'false'
        run: docker push ${{ secrets.DOCKER_USERNAME }}/github-action-schoolMariem
